/**
 * Words and phrases that mark a changelog line as written for developers, not for users.
 *
 * A release note answers "what changed for me"; a build tool, a test runner or an
 * internal field name never does. The list grew out of real review findings across
 * eleven adapters — it is deliberately blunt, and {@link CHANGELOG_PHRASE_ALLOWLIST}
 * carries the handful of accepted exceptions.
 */
export const TOOLING_PATTERNS: readonly string[] = [
  "npm-script",
  "npm-scripts",
  "package-lock",
  "package.json scripts",
  "dependabot",
  "tsconfig",
  "prettier.config",
  "prettier-config",
  "eslint",
  "format:check",
  "format:write",
  "nyc",
  "repochecker",
  "repochecker-version-gate",
  "workflow.yml",
  "test-and-release.yml",
  "auto-merge.yml",
  "tsconfig.test",
  "tsconfig.build",
  "build-test/",
  "@iobroker/eslint-config",
  "@types/node",
  "test/mocharc",
  "release-script-plugin",
  "manual-review",
  "mocha",
  "ts-node",
  "vitest",
  "rimraf",
  "typescript",
  "test runner",
  "test-runner",
  "linting toolchain",
  "release toolchain",
  "release-toolchain",
  "instanceobjects",
  "txt records",
  "capability shape",
  "adapter config shape",
  "extendobjectasync",
  "setobjectasync",
  "setforeignobjectasync",
  "protectednative",
  "encryptednative",
  "native field",
  "native key",
  "io-package.json",
  "io-package field",
  "ci tests",
  "ci matrix",
  "ci extended",
  "ci test matrix",
  "extended to node",
  "node.js matrix",
  "node matrix",
  "engines.node",
  "admin frontend",
  "race-free",
  "race-condition",
  "race protection",
  "race-protection",
  "post-mortem",
  "defensive guards",
  "defensive guard",
  "defensive cap-filter",
  "internal state-creation",
  "internal state creation",
  "internally",
  "internal refactor",
  "internal refactoring",
  "runs in clear phases",
  "runs in phases",
  "in phases — ",
  "no longer touches",
  "phase no longer touches",
  "phase doesn't touch",
  "phased state creation",
  "extracted to lib/",
  "extracted into lib/",
  "for unit-test coverage",
  "for testability",
  "tightened types",
  "removed `as any`",
  "removed any casts",
  "structured key=value",
  "structured key-value",
  "key=value details",
  "diagnostic aid",
  "diagnostic prefix",
  "one-time cleanup",
  "one time cleanup",
  "on first start of",
  "automatic migration on first start",
  "user-facing noise",
  "user facing noise",
  "not as user-facing",
  "diagnostic clutter",
  "defense-in-depth",
  "crash defense",
  "ultra-modernized",
  "comprehensive hardening",
  "comprehensive overhaul",
  "invalid json",
  "json parse",
  "parse error",
  "stack trace",
  "stack-trace",
  "plain-text response",
  "plain text response",
  "plain-text status",
  "plain text status",
  "plain-text body",
  "plain text body",
  "ble-cmds",
  "ble cmds",
  "ble commands",
  "ble command",
  "ptreal",
  "lan ptreal",
  "ptreal send",
  "ptreal sends",
  "udp error",
  "udp send",
  "udp datagram",
  "udp packet",
  "http 200",
  "http 403",
  "http 401",
  "http 500",
  "http-status",
  "fire-and-forget",
  "fire and forget",
  "no-op",
  "noop",
  "debug-confirm",
  "debug confirm",
  "debug-log line",
  "debug log line",
  "debug-log lines",
  "debug log lines",
  "log spam",
  "log-spam",
  "warn on udp",
  "warn-on-error",
  "warns on error",
  "log as warn",
  "log as a warn",
  "log a warn",
  "log a debug",
  "log as debug",
  "sticky cache",
  "sticky stale",
  "stale cache",
  "stale-cache",
  "cache-clear",
  "cache clear path",
  "cache file",
  "resolves null",
  "resolve as null",
  "null-resolve",
  "null resolve",
  "graceful-fail",
  "graceful fail",
  "silent fail",
  "silent-fail",
  "pattern #",
  "issue #13 follow-up",
  "issue follow-up",
  "multi-language object",
  "multi language object",
  "multilingual object",
  "i18n object",
  "i18n-object",
  "translation object",
  "translation-object",
  "couldn't render",
  "could not render",
  "doesn't render",
  "does not render",
  "fails to render",
  "fail to render",
  "cannot render",
  "can't render",
  "react node",
  "reactnode",
  "react error",
  "minified react",
  "react child",
  "valid as a react",
  "as a react child",
  "common.states",
  "common states",
  "state objects",
  "plain string",
  "plain-string",
  "plain-text label",
  "plain text label",
  "in the system language",
  "instead of a multi-language",
  "instead of a multilingual",
  "instead of an i18n",
  "is wired up",
  "are wired up",
  "now wired up",
  "now wired",
  "is wired",
  "wired live",
  "the flag",
  "the field",
  "the option",
  "the toggle",
  "the quirk",
  "the override",
  "is now active",
  "now active",
  "is now live",
  "now live",
  "is now in",
  "without an adapter update",
  "without a new release",
  "without releasing",
  "device-specific fix",
  "sku-specific fix",
  "per-sku fix",
  "per sku fix",
  "future device-specific",
  "future sku-specific",
  "future per-sku",
  "fixes ship",
  "shipped per-sku",
  "ship without",
  "adapter-managed",
  "adapter-core",
  "adapter-level",
  "handler pattern",
  "event handler",
  "event pattern",
  "community-standard",
  "community standard",
  "code quality",
  "standard formatting",
  "code formatting",
  "release-script",
  "release script",
  "i18n framework",
  "i18n-framework",
];

/** Patterns that need a regular expression rather than a plain word. */
export const TOOLING_REGEX_PATTERNS: readonly (readonly [RegExp, string])[] = [
  // Standalone "CI" — a CI change is always internal.
  [/\bci\b/, "CI-internal"],
  // Protocol plus action: "HTTP retry", "UDP send", "TCP timeout".
  [
    /\b(https?|udp|tcp|ble|mqtt|ws|sse|rest)\s+(retry|retries|send|sends|request|requests|response|responses|lifecycle|timeout|packet|datagram|call|calls|status\s+code)/,
    "protocol-internal",
  ],
  // Framework and library names: "adapter-core", "xxx-runtime".
  [/\b\w+[-.](core|framework|runtime|plugin|loader)\b/, "framework-name"],
  // Log level as the subject: "moved to debug level", "debug output".
  [
    /\b(debug|warn|error|info|silly)\s+(level|log(?:ging)?|trace|output)\b/,
    "log-mechanic",
  ],
  // Test counts: "+105 tests", "288→293 unit".
  [/[+→]\s*\d+\s*(tests?|unit)/, "test-count"],
];

/** Identifiers in backticks that users do know, because they see them in the object tree. */
export const TOOLING_BACKTICK_ALLOW: ReadonlySet<string> = new Set([
  "common.news",
  "common.states",
  "info.connection",
  "info.online",
  "system.config.language",
]);

/** camelCase or snake_case in backticks reads as source code, not as a user-facing name. */
export const TOOLING_BACKTICK_RE =
  /`[a-z]+[A-Z][a-zA-Z0-9]*`|`[a-z]+_[a-z][a-zA-Z0-9_]*`/g;

/** Phrases that are accepted verbatim even though they sound internal. */
export const CHANGELOG_PHRASE_ALLOWLIST: readonly string[] = [
  "internal cleanup. no user-facing changes.",
  "internal refactoring. no user-facing changes.",
];
